# Supervised Learning

Supervised learning Algorithms can be further divided into two types of problems:

![](https://static.javatpoint.com/tutorial/machine-learning/images/supervised-machine-learning-1.png)

# How Supervised Learning Works?

In supervised learning, models are trained using labelled dataset, where the model learns about each type of data. Once the training process is completed, the model is tested on the basis of test data (a subset of the training set), and then it predicts the output.

The working of Supervised learning can be easily understood by the below example and diagram:

![](https://static.javatpoint.com/tutorial/machine-learning/images/supervised-machine-learning.png)

Suppose we have a dataset of different types of shapes which includes square, rectangle, triangle, and Polygon. Now the first step is that we need to train the model for each shape.

If the given shape has four sides, and all the sides are equal, then it will be labelled as a Square.
If the given shape has three sides, then it will be labelled as a triangle.
If the given shape has six equal sides then it will be labelled as hexagon.
Now, after training, we test our model using the test set, and the task of the model is to identify the shape.

The machine is already trained on all types of shapes, and when it finds a new shape, it classifies the shape on the bases of a number of sides, and predicts the output.

# What Is Classification?
Classification is the process of recognizing, understanding, and grouping ideas and objects into preset categories or “sub-populations.” Using pre-categorized training datasets, machine learning programs use a variety of algorithms to classify future datasets into categories.

Classification algorithms in machine learning use input training data to predict the likelihood that subsequent data will fall into one of the predetermined categories. One of the most common uses of classification is filtering emails into “spam” or “non-spam.” 

In short, classification is a form of “pattern recognition,” with classification algorithms applied to the training data to find the same pattern (similar words or sentiments, number sequences, etc.) in future sets of data.

## Popular Classification Algorithms:
- Logistic Regression
- K-Nearest Neighbors
- Decision Tree
- Support Vector Machines
- Naive Bayes
- Stochastic Gradient Descent

# 1. Logistic Regression

Logistic regression is a calculation used to predict a binary outcome: either something happens, or does not. This can be exhibited as Yes/No, Pass/Fail, Alive/Dead, etc. 

Independent variables are analyzed to determine the binary outcome with the results falling into one of two categories. The independent variables can be categorical or numeric, but the dependent variable is always categorical. 

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/c6fbaf6182755b528d3232d60408a2414b6d76c1)

or

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/da88d81e6a0169ec2da7d7bc0e0f4efef4b9e2c7)

where usually b=exp().

![](https://miro.medium.com/max/875/1*RqXFpiNGwdiKBWyLJc_E7g.png)

## Types of Logistic Regression
1. Binary Logistic Regression:
The categorical response has only two 2 possible outcomes. Example: Spam or Not
2. Multinomial Logistic Regression:
Three or more categories without ordering. Example: Predicting which food is preferred more (Veg, Non-Veg, Vegan)
3. Ordinal Logistic Regression:
Three or more categories with ordering. Example: Movie rating from 1 to 5

## Estimation of coefficients
The regression coefficients are usually estimated using maximum likelihood estimation.

![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image1.jpeg)

Unlike linear regression, it is not possible to find a closed-form expression for the coefficient values that maximize the likelihood function, so that an iterative process must be used instead; 
for example:
- Newton's method 
- gradient descent 

This process begins with a tentative solution, revises it slightly to see if it can be improved, and repeats this revision until no more improvement is made, at which point the process is said to have converged.

# f(β), ∇f(β), and ∇²f(β)

f(β) = likelihood function

∇f(β) = the first derivative (gradient of f(β))

∇²f(β) = the second derivative (Hassian Matrix of f(β))

![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image2.1.jpeg)
![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image2.2.jpeg)
![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image2.3.jpeg)


## Source:
Owner of database: Volker Lohweg (University of Applied Sciences, Ostwestfalen-Lippe, volker.lohweg '@' hs-owl.de)

Donor of database: Helene Dörksen (University of Applied Sciences, Ostwestfalen-Lippe, helene.doerksen '@' hs-owl.de)

Date received: August, 2012

## Data Set Information:
Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.


## Attribute Information:
1. variance of Wavelet Transformed image (continuous) (X1)
2. skewness of Wavelet Transformed image (continuous) (X2)
3. curtosis of Wavelet Transformed image (continuous) (X3)
4. entropy of image (continuous) (X4)
5. class (integer) (Y)



## Imports

The first step is to import the package numpy and the class LinearRegression from sklearn.linear_model:

In [8]:
import pandas as pd
mydata = pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt",
        delimiter=",", header=0, names=["X1","X2","X3","X4","Y"])

In [9]:
mydata.shape[0]

1371

In [10]:
# get input "X1","X2","X3","X4"
inputX = mydata[["X1","X2","X3","X4"]].to_numpy()

In [11]:
import numpy as np

# define input X
X = np.matrix(np.ones(mydata.shape[0])).T
X = np.append(X,inputX,axis=1)

# define output Y
Y = mydata[["Y"]].to_numpy()

# Logistic Regression: Newton Raphson Approach

he Newton-Raphson method (also known as Newton's method) is a way to quickly find a good approximation for the root of a real-valued function f(x)=0. It uses the idea that a continuous and differentiable function can be approximated by a straight line tangent to it.

![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image2.5.jpeg)

## Define f(β), ∇f(β), and ∇²f(β)

![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image2.2.jpeg)
![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image2.3.jpeg)

In [12]:
# f(β)
def f(beta):
    return np.ravel(np.ones(len(Y))*(np.log(1+np.exp(X*beta)))-Y.T*X*beta)[0]

# ∇f(β)
def nabla_f(beta):
    return X.T*(1/(1+1/np.exp(X*beta))-Y)

# ∇²f(β)    
def nabla2_f(beta):
    return X.T*(np.diag(np.ravel(np.exp(X*beta)/np.power(1+np.exp(X*beta),2)))*X)

In [13]:
# Newton raphson Method
beta = np.matrix(np.zeros(X.shape[1])).T
TOL = np.power(10.,-10)
counter = 0

while np.linalg.norm(nabla_f(beta)) > TOL:
  counter += 1
  beta -= np.linalg.inv(nabla2_f(beta))*nabla_f(beta)
  
print('iter =',counter)
print(beta)
print('norm =',np.linalg.norm(nabla_f(beta)))

iter = 13
[[ 7.32180471]
 [-7.85933049]
 [-4.19096321]
 [-5.28743068]
 [-0.60531897]]
norm = 1.5942825815928695e-13


# Logistic Regression: Gradient Descent Approach

In [14]:
# Gradient Descent
beta = np.matrix(np.zeros(X.shape[1])).T
TOL = np.power(10.,-10)
lam = 0.001 # learning_rate
counter = 0

while np.linalg.norm(nabla_f(beta)) > TOL:
  counter += 1
  beta -= lam*nabla_f(beta)
    
print('iter =',counter)
print(beta)
print('norm =',np.linalg.norm(nabla_f(beta)))

iter = 164906
[[ 7.32180471]
 [-7.85933049]
 [-4.19096321]
 [-5.28743068]
 [-0.60531897]]
norm = 9.998916234054437e-11


In [15]:
# Classification Process
Xtest = [[1, 0.4,0.5,1.0,1.5]]
p = (np.exp(np.dot(Xtest, beta)) / (1 + np.exp(np.dot(Xtest, beta))))
p

matrix([[0.01609821]])

# Logistic Regression: Scikit-Learn

In [16]:
from sklearn.linear_model import LogisticRegression

# Newton-Conjugate Gradient
clf1 = LogisticRegression(penalty="none",solver='newton-cg',fit_intercept=False)
clf1.fit(X,np.ravel(Y))
print(clf1.coef_)

[[ 7.32180341 -7.85932911 -4.19096249 -5.28742975 -0.60531885]]


In [70]:
# Stochastic Average Gradient
clf2 = LogisticRegression(penalty="none",solver='sag',fit_intercept=False) 
clf2.fit(X,np.ravel(Y))
print(clf2.coef_)

[[ 4.17766542 -4.16803244 -2.3129587  -2.84284465 -0.22558116]]


C:\Users\rauzan\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "


## Classification Process

In [77]:
clf2.predict([[1, 0.4,0.5,1.0,1.5]])

array([0], dtype=int64)

# 2. K-Nearest Neighbors

K nearest neighbors is a simple algorithm used for classification. It basically stores all available cases to classify the new cases by a majority vote of its k neighbors. The case assigned to the class is most common amongst its K nearest neighbors measured by a distance function (Euclidean, Manhattan, Minkowski, and Hamming).

While the three former distance functions are used for continuous variables, the Hamming distance function is used for categorical variables. If K = 1, then the case is simply assigned to the class of its nearest neighbor. At times, choosing K turns out to be a challenge while performing kNN modeling.

## Distance metrics
![](https://raw.githubusercontent.com/rauzansumara/introduction-to-machine-learning/master/Material/image3.JPG)

## Propreties
- K-Nearest Neighbour is one of the simplest Machine Learning algorithms based on Supervised Learning technique.
- K-NN algorithm assumes the similarity between the new case/data and available cases and put the new case into the category that is most similar to the available categories.
- K-NN algorithm stores all the available data and classifies a new data point based on the similarity. This means when new data appears then it can be easily classified into a well suite category by using K- NN algorithm.
- K-NN is a non-parametric algorithm, which means it does not make any assumption on underlying data.
- It is also called a lazy learner algorithm because it does not learn from the training set immediately instead it stores the dataset and at the time of classification, it performs an action on the dataset.
- KNN algorithm at the training phase just stores the dataset and when it gets new data, then it classifies that data into a category that is much similar to the new data.
- Example: Suppose, we have an image of a creature that looks similar to cat and dog, but we want to know either it is a cat or dog. So for this identification, we can use the KNN algorithm, as it works on a similarity measure. Our KNN model will find the similar features of the new data set to the cats and dogs images and based on the most similar features it will put it in either cat or dog category.

![](https://static.javatpoint.com/tutorial/machine-learning/images/k-nearest-neighbor-algorithm-for-machine-learning.png)

## Why do we need a K-NN Algorithm?

Suppose there are two categories, i.e., Category A and Category B, and we have a new data point x1, so this data point will lie in which of these categories. To solve this type of problem, we need a K-NN algorithm. With the help of K-NN, we can easily identify the category or class of a particular dataset. Consider the below diagram:

![](https://static.javatpoint.com/tutorial/machine-learning/images/k-nearest-neighbor-algorithm-for-machine-learning2.png)

## How does K-NN work?

The K-NN working can be explained on the basis of the below algorithm:

- Step-1: Select the number K of the neighbors
- Step-2: Calculate the Euclidean distance of K number of neighbors
- Step-3: Take the K nearest neighbors as per the calculated Euclidean distance.
- Step-4: Among these k neighbors, count the number of the data points in each category.
- Step-5: Assign the new data points to that category for which the number of the neighbor is maximum.
- Step-6: Our model is ready.

Suppose we have a new data point and we need to put it in the required category. Consider the below image:

![](https://static.javatpoint.com/tutorial/machine-learning/images/k-nearest-neighbor-algorithm-for-machine-learning3.png)

- Firstly, we will choose the number of neighbors, so we will choose the k=5.
- Next, we will calculate the Euclidean distance between the data points. The Euclidean distance is the distance between two points, which we have already studied in geometry. It can be calculated as:

![](https://static.javatpoint.com/tutorial/machine-learning/images/k-nearest-neighbor-algorithm-for-machine-learning4.png)

- By calculating the Euclidean distance we got the nearest neighbors, as three nearest neighbors in category A and two nearest neighbors in category B. Consider the below image:

![](https://static.javatpoint.com/tutorial/machine-learning/images/k-nearest-neighbor-algorithm-for-machine-learning5.png)

- As we can see the 3 nearest neighbors are from category A, hence this new data point must belong to category A.

## Things to Consider Before Selecting KNN:
- KNN is computationally expensive
- Variables should be normalized else higher range variables can bias it
- Works on pre-processing stage more before going for kNN like an outlier, noise removal

In [185]:
from scipy import stats

df = pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt",
        delimiter=",", header=0, names=["X1","X2","X3","X4","Y"])

X = df[["X1","X2","X3","X4"]].to_numpy()
Y = df[["Y"]].to_numpy()

In [186]:
# Feature Scaling (MinMax Normalize) 
def NormalizeData(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Normalize dataset
datX = NormalizeData(X)

In [187]:
# Generate random values
nr = np.arange(datX.shape[0])

# shuffle datasets
training_ratio = 0.8
np.random.shuffle(nr)
datX = datX[nr] # shuffle X
datY = Y[nr] # shuffle Y

# set 80% train and 20% test sets
nr_split = np.round(datX.shape[0]*training_ratio, 0).astype(np.int)

# Divide data into train and test sets
X_train = datX[:nr_split, :]
y_train = datY[:nr_split]
X_test = datX[nr_split:, :]
y_test = datY[nr_split:]

In [191]:
# Create kNN function
def knn_classifier(X_train, y_train, X_test, k):
    A = np.expand_dims(X_test, axis=1) 
    B = np.expand_dims(X_train, axis = 0)
    X_tensor = A - B

    D = np.sqrt(np.sum(np.power(X_tensor, 2), axis=2))
    nr = np.argsort(D, axis = 1)
    return stats.mode(y_train[nr][:,:k], axis = 1)[0][:,0]

# call k-NN function
y_test_est = knn_classifier(X_train, y_train, X_test, k = 3)

1.0


In [192]:
# result
y_test_est[:10]

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]], dtype=int64)

# 2. K-Nearest Neighbors: Scikit-Learn

In [ ]:
# # Splitting the dataset into training and test set.  
# from sklearn.model_selection import train_test_split  
# X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.20, random_state=0)  

# # Normalize Data
# from sklearn.preprocessing import MinMaxScaler    
# st_x = MinMaxScaler()    
# x_train = st_x.fit_transform(X_train)    
# x_test = st_x.transform(X_test)  

In [193]:
# Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)  
classifier.fit(X_train, np.ravel(y_train))

KNeighborsClassifier(n_neighbors=3)

In [194]:
# Predicting the test set  
y_pred = classifier.predict(X_test)

In [195]:
y_pred[:10]

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0], dtype=int64)